on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [31]
        target: [default]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          ram-size: 4096M
          sdcard-path-or-size: 4096M
          script: ./e2e.sh --CI

      - name: E2E tests results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
          name: e2e-tests-results
          path: output/